import Providers from "./components/Providers";
import "./globals.css";
import { Manrope, Red_Hat_Display } from "next/font/google";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-radHatDisplay",
});
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-manrope",
});
export const metadata = {
  title: "Makinft - NFT Marketplac",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${redHatDisplay.variable} ${manrope.variable}`}
    >
      <body className=" bg-gray-100 dark:bg-navy-300">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
